spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whrkflow_dev
    username: whrkflow_user
    password: whrkflow_pass

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: DEBUG
    com.whrkflow: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
