spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/werkflow_dev
    username: werkflow_user
    password: werkflow_pass

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: DEBUG
    com.werkflow: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
